server:
  port: 7501
spring:
    application:
        name: gateway
## api-aaa指模块名
## 这里的配置表示，访问/mv/** 直接重定向到https://mvnrepository.com/**
#zuul:
#  routes:
#    api-aaa:
#      path: /mv/**
#      url: https://mvnrepository.com/
#  routes:
#    api-cons:
#      path: /cons/**
#      serviceId: eureka-consumer
eureka:
  client:
    # 注册中心地址
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/