# 端口号
server:
  port: 7301
# 服务名称
spring:
  application:
    name: eureka-consumer
# 服务注册与发现相关配置
eureka:
  instance:
    hostname: consumer1
  client:
    # 注册中心地址
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/

#      启动熔断器
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
        exposure:
          include: "*"
          exclude: env,beans
